DEBUG 2021-06-11 16:21:00.376 UTC: 	 CRAB Client version: v3.210601
DEBUG 2021-06-11 16:21:00.376 UTC: 	 Running on: Linux naf-cms13.desy.de 3.10.0-1160.21.1.el7.x86_64 #1 SMP Tue Mar 16 18:28:22 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-06-11 16:21:00.376 UTC: 	 Executing command: 'status'
DEBUG 2021-06-11 16:21:00.377 UTC: 	 Found CRAB cache file /afs/desy.de/user/h/hugobg/.crab3
ERROR 2021-06-11 16:21:00.378 UTC: 	 Error: crab_Test/crab_TTToSemiLeptonic_TuneCP5_PSweights_13TeV-powheg-pythia8_Summer16_v1 is not a valid CRAB project directory.
ERROR 2021-06-11 16:21:00.378 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_Test/crab_TTToSemiLeptonic_TuneCP5_PSweights_13TeV-powheg-pythia8_Summer16_v1 is not a valid CRAB project directory.
INFO 2021-06-11 16:21:00.381 UTC: 	 Log file is /nfs/dust/cms/user/hugobg/UHH2_v2/CMSSW_10_2_17/src/UHH2/Analysis/tres_categorias_muon_CHS/crab.log
